apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-fastify
  labels:
    app: deno-fastify
spec:
  selector:
    matchLabels:
      app: deno-fastify
  template:
    metadata:
      labels:
        app: deno-fastify
    spec:
      containers:
        - name: deno-fastify
          image: deno-fastify-image
          ports:
            - containerPort: 3000
