apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-fastify
  labels:
    app: deno-fastify
    # sablier.enable: "true"
    # sablier.group: deno-api-services
spec:
  selector:
    matchLabels:
      app: deno-fastify
  template:
    metadata:
      labels:
        app: deno-fastify
    spec:
      containers:
        - name: deno-fastify
          image: deno-fastify-image
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deno-fastify-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deno-fastify
                port:
                  name: web-alt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: my-sablier
spec:
  plugin:
    sablier:
      group: default
      dynamic:
        displayName: My Title
        refreshFrequency: 5s
        showDetails: "true"
        theme: hacker-terminal
      sablierUrl: http://sablier:10000
      sessionDuration: 1m
