apiVersion: v1
kind: ServiceAccount
metadata:
  name: sablier-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sablier-role
rules:
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments
      - statefulsets
    verbs:
      - get # Retrieve info about specific dep
      - list # Events
      - watch # Events
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - patch # Scale up and down
      - update # Scale up and down
      - get # Retrieve info about specific dep
      - list # Events
      - watch # Events
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sablier-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sablier-role
subjects:
  - kind: ServiceAccount
    name: sablier-account
    namespace: default # This tutorial uses the "default" K8s namespace.
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sablier
  labels:
    app: sablier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sablier
  template:
    metadata:
      labels:
        app: sablier
    spec:
      serviceAccountName: sablier-account
      containers:
        - name: sablier
          image: sablier-image
          ports:
            - containerPort: 10000
