kind: Deployment
apiVersion: apps/v1
metadata:
  name: deno-hono
  labels:
    app: deno-hono
    # sablier.enable: "true"
    # sablier.group: deno-api-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deno-hono
  template:
    metadata:
      labels:
        app: deno-hono
    spec:
      containers:
        - name: deno-hono
          image: deno-hono-image
          ports:
            - name: web
              containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: deno-hono
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: deno-hono
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deno-hono-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deno-hono
                port:
                  name: web
